version: '3.8'
services:
  db:
    image: postgres:13
    env_file:
      - ./user-service/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    depends_on:
      - db
    build: ./user-service
    ports:
      - "5000:5000"
    image: user-service:latest
    env_file:
      - ./user-service/.env

volumes:
  db-data: 
