services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass 
  notification-service:
    build: ./notification-service
    ports:
      - "5003:5003"
    image: notification-service:latest
    env_file:
      - ./notification-service/.env
  order-service:
    build: 
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "5002:5002"
    image: order-service:latest
    env_file:
      - ./order-service/.env
  product-service:
    depends_on:
      - mongodb
    build: 
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "5001:5001"
      - "5051:5051"
    image: product-service:latest
    env_file:
      - ./product-service/.env
  user-service:
    env_file:
      - ./user-service/.env
    depends_on:
      - db-user
    build: ./user-service
    ports:
      - "5000:5000"
    image: user-service:latest
  mongodb:
    image: mongo:7.0
    env_file:
      - ./product-service/.env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  db-order:
    image: postgres:13
    env_file:
      - ./order-service/.env
    volumes:
      - db-data-order:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  db-user:
    image: postgres:13
    env_file:
      - ./user-service/.env
    volumes:
      - db-data-user:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes:
  db-data-user:
  mongo-data:
  db-data-order:
