syntax = "proto3";

package products;

service ProductsService {
  rpc FindOne (FindOneRequest) returns (Product);
  rpc FindByIds (FindManyRequest) returns (ProductsList);
  rpc DecreaseStock (DecreaseStockRequest) returns (Product);
}
message DecreaseStockRequest {
  string id = 1;
  int32 quantity = 2;
}

// Mensaje para peticiones que buscan múltiples productos por sus IDs
message FindManyRequest {
  repeated string ids = 1;
}
// Mensaje para devolver una lista de productos
message ProductsList {
  repeated Product products = 1;
}
// Mensaje para peticiones que no envían datos
message Empty {}

// Mensaje Define qué datos necesita el método FindOne
message FindOneRequest {
  string id = 1;
}

// Mensaje 'Product'
message Product {
  string id = 1;
  string name = 2;
  int32 price = 3;
  string category = 4;
  string description = 5;
  string stock = 6;
}
